#!/usr/bin/env bash
set -euo pipefail

PATH_SEG='#(~/.config/tmux/scripts/path-smart #{client_width} "#{pane_current_path}")'
GIT_SEG='#(BR_ICON="#{@branch_icon}" bash ~/.config/tmux/scripts/git-info "#{pane_current_path}")'
SESSION_SEG='#(~/.config/tmux/scripts/session-name "#{session_id}" "#{pane_current_path}")'

tmux set -g status-left "#[fg=#{@SAPPHIRE},bold] 󰍹 #H #[fg=#{@OVERLAY0}] | #[fg=#{@PINK}] ${SESSION_SEG} "
tmux set -g status-right "#[fg=#{@SURFACE2}] #{@icon_folder} ${PATH_SEG} #{?#{!=:${GIT_SEG},},#[fg=#{@OVERLAY0}] | #[fg=#{@PEACH}] ${GIT_SEG} ,}#[fg=#{@OVERLAY0}] | #[fg=#{@ROSEWATER}]  %H:%M "
