{
  modules = [
    "pipewire"
    "bluetooth"
    "fonts"
    "fuzzel"
    "ly"
    "adwaita-dark"
    "papirus"
    "bibata"
    "wallpapers"
    "librewolf"
    "firefox"
    "zen-browser"
    "ghostty"
    "zed"
    "niri"
    "kde"
    # "hyprland"
    # "hypridle"
    # "hyprlock"
    "quickshell"
    "noctalia"
    "mako"
    "polkit-gnome"
    "xwayland-satellite"
    "swww"
    "waybar"
    "wl-clipboard"
    "wayland"
    "grim"
    "slurp"
    "brightnessctl"
    "pavucontrol"
    "playerctl"
    "gnome-keyring"
    "power-profiles-daemon"
    "upower"
    "networkmanagerapplet"
    "intel"
  ];
}
