{
  components = [
    "xdg-wayland"
    "fonts"
    "bibata-cursor"
    "launcher"
    "ly"
    "theme-dark"
    "wallpapers"
    "browsers"
    "niri"
    "kde"
    # "hyprland"
    # "hypridle"
    # "hyprlock"
    "quickshell"
    "noctalia-shell"
    "power-management"
    "notifications"
    "secret-service"
    "polkit-agent"
    "xwayland-satellite"
    "swww"
    "waybar"
    "wl-clipboard"
    "grim"
    "slurp"
    "brightnessctl"
    "pavucontrol"
    "playerctl"
    "networkmanager-applet"
  ];
}
